"""
Project Configuration Models

This module defines the data structures for project configuration using Pydantic.
"""

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class PackageManager(str, Enum):
    """Supported package managers."""

    UV = "uv"
    POETRY = "poetry"
    PIP = "pip"


class DatabaseType(str, Enum):
    """Supported database types."""

    POSTGRES = "postgres"
    MYSQL = "mysql"
    SQLITE = "sqlite"
    NONE = "none"


class ProjectConfig(BaseModel):
    """
    Project configuration model.

    This model holds all the configuration options for generating a new FastAPI project.
    """

    # Basic Information
    project_name: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Name of the project",
    )
    project_slug: str = Field(
        default="",
        description="Project identifier in snake_case",
    )
    project_description: str = Field(
        default="A FastAPI project generated by FastAPI-Forge",
        description="Project description",
    )
    author_name: str = Field(
        default="Your Name",
        description="Author name",
    )
    author_email: str = Field(
        default="your@email.com",
        description="Author email",
    )
    python_version: Literal["3.10", "3.11", "3.12", "3.13"] = Field(
        default="3.11",
        description="Python version",
    )

    # Package Manager
    package_manager: PackageManager = Field(
        default=PackageManager.UV,
        description="Package manager to use",
    )

    # Database
    database: DatabaseType = Field(
        default=DatabaseType.POSTGRES,
        description="Database type",
    )
    use_alembic: bool = Field(
        default=True,
        description="Whether to use Alembic for database migrations",
    )

    # Features
    use_auth: bool = Field(
        default=True,
        description="Whether to include JWT authentication",
    )
    use_redis: bool = Field(
        default=True,
        description="Whether to include Redis support",
    )

    # Docker
    use_docker: bool = Field(
        default=True,
        description="Whether to generate Docker configuration",
    )
    use_docker_compose: bool = Field(
        default=True,
        description="Whether to generate docker-compose.yml",
    )
    docker_services: list[str] = Field(
        default_factory=lambda: ["postgres", "redis"],
        description="Services to include in docker-compose",
    )

    # Testing & Quality
    use_pytest: bool = Field(
        default=True,
        description="Whether to configure Pytest",
    )
    use_ruff: bool = Field(
        default=True,
        description="Whether to configure Ruff linter/formatter",
    )

    # CI/CD & Editor
    use_github_actions: bool = Field(
        default=True,
        description="Whether to generate GitHub Actions CI",
    )
    use_vscode: bool = Field(
        default=True,
        description="Whether to generate VS Code configuration",
    )

    @field_validator("project_slug", mode="before")
    @classmethod
    def generate_slug(cls, v: str, info) -> str:
        """Generate project slug from project name if not provided."""
        if v:
            return v
        # Get project_name from the data being validated
        project_name = info.data.get("project_name", "")
        if project_name:
            # Convert to snake_case
            slug = project_name.lower()
            slug = slug.replace("-", "_")
            slug = slug.replace(" ", "_")
            # Remove any non-alphanumeric characters except underscore
            slug = "".join(c for c in slug if c.isalnum() or c == "_")
            return slug
        return v

    def model_post_init(self, __context) -> None:
        """Post-initialization processing."""
        # Ensure project_slug is set
        if not self.project_slug and self.project_name:
            slug = self.project_name.lower()
            slug = slug.replace("-", "_")
            slug = slug.replace(" ", "_")
            slug = "".join(c for c in slug if c.isalnum() or c == "_")
            object.__setattr__(self, "project_slug", slug)

        # If database is none, disable alembic
        if self.database == DatabaseType.NONE:
            object.__setattr__(self, "use_alembic", False)

        # Update docker_services based on selections
        services = []
        if self.database == DatabaseType.POSTGRES:
            services.append("postgres")
        elif self.database == DatabaseType.MYSQL:
            services.append("mysql")
        if self.use_redis:
            services.append("redis")
        if services != self.docker_services:
            object.__setattr__(self, "docker_services", services)


# Default configuration for quick start
DEFAULT_CONFIG = ProjectConfig(
    project_name="my-fastapi-app",
    project_description="A FastAPI project generated by FastAPI-Forge",
    author_name="Your Name",
    author_email="your@email.com",
    python_version="3.11",
    package_manager=PackageManager.UV,
    database=DatabaseType.POSTGRES,
    use_alembic=True,
    use_auth=True,
    use_redis=True,
    use_docker=True,
    use_docker_compose=True,
    use_pytest=True,
    use_ruff=True,
    use_github_actions=True,
    use_vscode=True,
)
