"""
Interactive Prompts Module

This module provides interactive command-line prompts using Questionary
for collecting project configuration from users.
"""

import questionary
from questionary import Style
from rich.console import Console

from fastapi_forge.models import (
    DatabaseType,
    PackageManager,
    ProjectConfig,
)

console = Console()

# Custom style for questionary prompts
CUSTOM_STYLE = Style(
    [
        ("qmark", "fg:cyan bold"),
        ("question", "fg:white bold"),
        ("answer", "fg:green bold"),
        ("pointer", "fg:cyan bold"),
        ("highlighted", "fg:cyan bold"),
        ("selected", "fg:green"),
        ("separator", "fg:gray"),
        ("instruction", "fg:gray italic"),
        ("text", "fg:white"),
    ]
)


def prompt_basic_info(project_name: str | None = None) -> dict:
    """
    Prompt for basic project information.

    Args:
        project_name: Optional pre-filled project name

    Returns:
        Dictionary with basic project info
    """
    console.print("\n[bold cyan]📝 Basic Project Information[/bold cyan]\n")

    # Project name
    if project_name:
        name = project_name
        console.print(f"  Project name: [green]{name}[/green]")
    else:
        name = questionary.text(
            "Project name:",
            default="my-fastapi-app",
            style=CUSTOM_STYLE,
        ).ask()

    if not name:
        raise KeyboardInterrupt("Project creation cancelled.")

    # Project description
    description = questionary.text(
        "Project description:",
        default="A FastAPI project generated by FastAPI-Forge",
        style=CUSTOM_STYLE,
    ).ask()

    # Author name
    author_name = questionary.text(
        "Author name:",
        default="Your Name",
        style=CUSTOM_STYLE,
    ).ask()

    # Author email
    author_email = questionary.text(
        "Author email:",
        default="your@email.com",
        style=CUSTOM_STYLE,
    ).ask()

    # Python version
    python_version = questionary.select(
        "Python version:",
        choices=["3.10", "3.11", "3.12", "3.13"],
        default="3.11",
        style=CUSTOM_STYLE,
    ).ask()

    return {
        "project_name": name,
        "project_description": description or "A FastAPI project",
        "author_name": author_name or "Your Name",
        "author_email": author_email or "your@email.com",
        "python_version": python_version or "3.11",
    }


def prompt_package_manager() -> PackageManager:
    """
    Prompt for package manager selection.

    Returns:
        Selected PackageManager enum value
    """
    console.print("\n[bold cyan]📦 Package Manager[/bold cyan]\n")

    choice = questionary.select(
        "Select package manager:",
        choices=[
            questionary.Choice("uv (recommended - faster)", value="uv"),
            questionary.Choice("Poetry", value="poetry"),
            questionary.Choice("pip (requirements.txt only)", value="pip"),
        ],
        default="uv",
        style=CUSTOM_STYLE,
    ).ask()

    return PackageManager(choice) if choice else PackageManager.UV


def prompt_database() -> tuple[DatabaseType, bool]:
    """
    Prompt for database configuration.

    Returns:
        Tuple of (DatabaseType, use_alembic)
    """
    console.print("\n[bold cyan]🗄️  Database Configuration[/bold cyan]\n")

    db_choice = questionary.select(
        "Select database:",
        choices=[
            questionary.Choice("PostgreSQL (recommended)", value="postgres"),
            questionary.Choice("MySQL", value="mysql"),
            questionary.Choice("SQLite (development only)", value="sqlite"),
            questionary.Choice("None (no database)", value="none"),
        ],
        default="postgres",
        style=CUSTOM_STYLE,
    ).ask()

    database = DatabaseType(db_choice) if db_choice else DatabaseType.POSTGRES

    use_alembic = False
    if database != DatabaseType.NONE:
        use_alembic = questionary.confirm(
            "Enable database migrations (Alembic)?",
            default=True,
            style=CUSTOM_STYLE,
        ).ask()
        use_alembic = use_alembic if use_alembic is not None else True

    return database, use_alembic


def prompt_features() -> dict:
    """
    Prompt for feature selection.

    Returns:
        Dictionary with feature flags
    """
    console.print("\n[bold cyan]🔧 Features[/bold cyan]\n")

    use_auth = questionary.confirm(
        "Include JWT authentication module?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    use_redis = questionary.confirm(
        "Include Redis support?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    return {
        "use_auth": use_auth if use_auth is not None else True,
        "use_redis": use_redis if use_redis is not None else True,
    }


def prompt_docker() -> dict:
    """
    Prompt for Docker configuration.

    Returns:
        Dictionary with Docker settings
    """
    console.print("\n[bold cyan]🐳 Docker Configuration[/bold cyan]\n")

    use_docker = questionary.confirm(
        "Generate Dockerfile?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()
    use_docker = use_docker if use_docker is not None else True

    use_docker_compose = False
    docker_services: list[str] = []

    if use_docker:
        use_docker_compose = questionary.confirm(
            "Generate docker-compose.yml?",
            default=True,
            style=CUSTOM_STYLE,
        ).ask()
        use_docker_compose = use_docker_compose if use_docker_compose is not None else True

        if use_docker_compose:
            docker_services = questionary.checkbox(
                "Select services for docker-compose:",
                choices=[
                    questionary.Choice("PostgreSQL", value="postgres", checked=True),
                    questionary.Choice("Redis", value="redis", checked=True),
                    questionary.Choice("RabbitMQ", value="rabbitmq"),
                    questionary.Choice("MinIO (Object Storage)", value="minio"),
                ],
                style=CUSTOM_STYLE,
            ).ask()
            docker_services = docker_services or ["postgres", "redis"]

    return {
        "use_docker": use_docker,
        "use_docker_compose": use_docker_compose,
        "docker_services": docker_services,
    }


def prompt_extras() -> dict:
    """
    Prompt for extra configuration options.

    Returns:
        Dictionary with extra settings
    """
    console.print("\n[bold cyan]✨ Extra Options[/bold cyan]\n")

    use_pytest = questionary.confirm(
        "Configure Pytest for testing?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    use_ruff = questionary.confirm(
        "Configure Ruff (linter/formatter)?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    use_github_actions = questionary.confirm(
        "Generate GitHub Actions CI?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    use_vscode = questionary.confirm(
        "Generate VS Code configuration?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    return {
        "use_pytest": use_pytest if use_pytest is not None else True,
        "use_ruff": use_ruff if use_ruff is not None else True,
        "use_github_actions": use_github_actions if use_github_actions is not None else True,
        "use_vscode": use_vscode if use_vscode is not None else True,
    }


def collect_project_config(project_name: str | None = None) -> ProjectConfig:
    """
    Collect all project configuration through interactive prompts.

    Args:
        project_name: Optional pre-filled project name

    Returns:
        Complete ProjectConfig object
    """
    console.print(
        "\n[bold cyan]🚀 FastAPI-Forge[/bold cyan] - "
        "[white]Create New Project[/white]\n"
    )
    console.print("[dim]Press Ctrl+C to cancel at any time.[/dim]\n")

    try:
        # Collect all configuration
        basic_info = prompt_basic_info(project_name)
        package_manager = prompt_package_manager()
        database, use_alembic = prompt_database()
        features = prompt_features()
        docker = prompt_docker()
        extras = prompt_extras()

        # Combine all config
        config = ProjectConfig(
            **basic_info,
            package_manager=package_manager,
            database=database,
            use_alembic=use_alembic,
            **features,
            **docker,
            **extras,
        )

        return config

    except KeyboardInterrupt:
        console.print("\n\n[yellow]Project creation cancelled.[/yellow]")
        raise


def confirm_config(config: ProjectConfig) -> bool:
    """
    Display configuration summary and ask for confirmation.

    Args:
        config: ProjectConfig to display

    Returns:
        True if user confirms, False otherwise
    """
    console.print("\n[bold cyan]📋 Configuration Summary[/bold cyan]\n")

    console.print(f"  [white]Project:[/white] [green]{config.project_name}[/green]")
    console.print(f"  [white]Description:[/white] {config.project_description}")
    console.print(f"  [white]Author:[/white] {config.author_name} <{config.author_email}>")
    console.print(f"  [white]Python:[/white] {config.python_version}")
    console.print(f"  [white]Package Manager:[/white] {config.package_manager.value}")
    console.print(f"  [white]Database:[/white] {config.database.value}")

    features = []
    if config.use_alembic:
        features.append("Alembic")
    if config.use_auth:
        features.append("JWT Auth")
    if config.use_redis:
        features.append("Redis")
    if config.use_docker:
        features.append("Docker")
    if config.use_pytest:
        features.append("Pytest")
    if config.use_ruff:
        features.append("Ruff")
    if config.use_github_actions:
        features.append("GitHub Actions")

    console.print(f"  [white]Features:[/white] {', '.join(features)}")

    if config.use_docker_compose and config.docker_services:
        console.print(f"  [white]Docker Services:[/white] {', '.join(config.docker_services)}")

    console.print()

    confirm = questionary.confirm(
        "Create project with this configuration?",
        default=True,
        style=CUSTOM_STYLE,
    ).ask()

    return confirm if confirm is not None else False
